version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - SPOTIPY_CLIENT_ID=your-client-id
      - SPOTIPY_CLIENT_SECRET=your-client-secret
      - SPOTIPY_REDIRECT_URI=http://localhost:8000/callback

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "serve -s /app/build -l 3000"
